using System;

namespace PN3D.Validate
{
    /// <summary>
    /// Verifies the C# port against the shipping JavaScript. Exits non-zero on any
    /// mismatch so it can gate a commit.
    ///
    /// The golden references are generated by extracting the real functions out of
    /// src/*.js by text and evaluating them, so this diffs against the shipped code
    /// rather than against hand-written expectations:
    ///
    ///   node tools/gen_golden_routes.js
    ///   node tools/gen_golden_physics.js
    ///
    /// Pass "routes" or "physics" to run a single suite; default is both.
    /// </summary>
    internal static class Program
    {
        static int Main(string[] args)
        {
            string repo = Checks.FindRepoRoot();
            Console.WriteLine($"repo    : {repo}");

            bool routes = args.Length == 0 || Array.IndexOf(args, "routes") >= 0;
            bool physics = args.Length == 0 || Array.IndexOf(args, "physics") >= 0;
            bool parking = args.Length == 0 || Array.IndexOf(args, "parking") >= 0;
            bool scoring = args.Length == 0 || Array.IndexOf(args, "scoring") >= 0;
            bool actors = args.Length == 0 || Array.IndexOf(args, "actors") >= 0;

            if (routes) RouteSuite.Run(repo);
            if (physics) PhysicsSuite.Run(repo);
            if (parking) ParkingSuite.Run(repo);
            if (scoring) ScoringSuite.Run(repo);
            if (actors) ActorsSuite.Run(repo);

            Console.WriteLine();
            Console.WriteLine($"{Checks.Count} checks");
            Console.WriteLine($"max relative drift vs JS: {Checks.MaxRelDrift:E3} " +
                              $"(tolerance {Checks.Eps:E0}) at {Checks.MaxRelWhere}");

            if (Checks.Failures.Count == 0)
            {
                Console.WriteLine("PASS — C# core matches the JavaScript reference");
                return 0;
            }

            Console.WriteLine($"FAIL — {Checks.Failures.Count} mismatch(es):");
            int show = Math.Min(Checks.Failures.Count, 40);
            for (int i = 0; i < show; i++) Console.WriteLine("  " + Checks.Failures[i]);
            if (Checks.Failures.Count > show)
                Console.WriteLine($"  ... and {Checks.Failures.Count - show} more");
            return 1;
        }
    }
}
